package main.java.com.brian.Java_Files.hibernateFiles3;

// Generated May 22, 2016 12:26:28 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Videos generated by hbm2java
 */
@Entity
@Table(name = "videos", catalog = "utube_schema")
public class Videos implements java.io.Serializable {

	private Integer idVideos;
	private String videoTitle;
	private String videoId;

	public Videos() {
	}

	public Videos(String videoTitle, String videoId) {
		this.videoTitle = videoTitle;
		this.videoId = videoId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idVideos", unique = true, nullable = false)
	public Integer getIdVideos() {
		return this.idVideos;
	}

	public void setIdVideos(Integer idVideos) {
		this.idVideos = idVideos;
	}

	@Column(name = "videoTitle", nullable = false, length = 45)
	public String getVideoTitle() {
		return this.videoTitle;
	}

	public void setVideoTitle(String videoTitle) {
		this.videoTitle = videoTitle;
	}

	@Column(name = "videoId", nullable = false, length = 45)
	public String getVideoId() {
		return this.videoId;
	}

	public void setVideoId(String videoId) {
		this.videoId = videoId;
	}

}
